version: '3.7'

services:
  tile_server:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub:tileserver
    environment:
      DATABASE_URL: postgres://bbnavihub@bbnavi-datahub-postgresql/bbnavihub
    command: "martin --config /martin_config.yml"
    # configs:
    #   - source: martin-config-yml-2022-05-19
    #     target: /martin_config.yml
    networks:
      - bbnavi-datahub-postgresql
      - public

  redis:
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    image: docker.io/bitnami/redis:6.0-debian-10
    networks:
      bbnavi-redis-server:
        aliases:
        - bbnavi-redis-server
    volumes:
     - redis_data:/bitnami/redis/data:rw

  delayed_job:
    image: ghcr.io/citygo-es/citygo-datahub:master
    command: bin/delayed_job run
    networks:
      - bbnavi-datahub-postgresql
      - bbnavi-redis-server
    environment:
      SVA_COMMUNITY: bbnavi
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
      - source:  bbnavi-datahub-credentials
        target: /app/releases/bbnavi/credentials.yml
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == node-001.tpwd-bb-navi

  cron_job:
    image: ghcr.io/citygo-es/citygo-datahub:master
    command: bin/start-cron.sh
    environment:
      SVA_COMMUNITY: bbnavi
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    networks:
      - bbnavi-datahub-postgresql
      - bbnavi-redis-server
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
      - source:  bbnavi-datahub-credentials
        target: /app/releases/bbnavi/credentials.yml
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == node-001.tpwd-bb-navi

  app:
    image: ghcr.io/citygo-es/citygo-datahub:master
    environment:
      SVA_COMMUNITY: bbnavi
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: mainserver-common-master-key
        target: /app/config/master.key
      - source:  bbnavi-datahub-credentials
        target: /app/releases/bbnavi/credentials.yml
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    networks:
      - bbnavi-datahub-postgresql
      - bbnavi-redis-server
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == node-001.tpwd-bb-navi

  nginx:
    image: nginx
    networks: [default, public]
    configs:
      - source: datahub-nginx-conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - unicorn:/unicorn
      - assets:/public
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == node-001.tpwd-bb-navi

  db:
    # image: 'postgres:10.3-alpine'
    image: 'postgis/postgis:15-3.3'
    environment:
      POSTGRES_USER: bbnavihub
      POSTGRES_PASSWORT: bbnavihub
      POSTGRES_PASSWORD: bbnavihub
      POSTGRES_DB: bbnavihub
      POSTGRES_HOST_AUTH_METHOD: trust
      DATADIR: /var/lib/postgresql/data
    networks:
      bbnavi-datahub-postgresql:
        aliases:
          - bbnavi-datahub-postgresql
    volumes:
      - datahub_postgres_15_production_db:/var/lib/postgresql/data:rw
      # old db backup in volume 'datahub_db'
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == node-001.tpwd-bb-navi

volumes:
  datahub_postgres_15_production_db:
    external: true
  redis_data:
    external: true
  unicorn:
  assets:
  ssh_public_keys:
    external: true

configs:
  bbnavi-datahub-credentials:
    external: true
  mainserver-common-master-key:
    external: true
  datahub-nginx-conf:
    external: true

networks:
  public:
    external: true
  bbnavi-datahub-postgresql:
    external: true
  bbnavi-redis-server:
    external: true
